### PR TITLE
Doc as webpage with PDF gen

### PR DESCRIPTION
**Pull request by jack-watts**
Initial commit of source code for Web page representation of the document with PDF generation support.

### CODE REVIEW

**Comment by palemieux** [comment]
@jack-watts `npm run lint` dies painfully. Can advise, fix or remove?

**Review by palemieux — CHANGES_REQUESTED** [review]
Why is yarn required when npm is used?

**Comment by palemieux** [comment]
For the scope, I suggest the following:

_This best practice defines terms used in IMF workflows._

**Comment by jack-watts** [comment]
> For the scope, I suggest the following:
> 
> _This best practice defines terms used in IMF workflows._

That change has been made.

**Comment by jack-watts** [comment]
> Why is yarn required when npm is used?

This is just out of the habit of using yarn over npm from Vue 1.0. I've changed to npm.

**Comment by jack-watts** [comment]
> @jack-watts `npm run lint` dies painfully. Can advise, fix or remove?

@palemieux  This is fixed. See Commit: [56c5be0c95211ec4c5d3e81ab9f0fe8eecf0b890](https://github.com/imfug/002-pkg-and-delivery/pull/24/commits/56c5be0c95211ec4c5d3e81ab9f0fe8eecf0b890)

**Review by palemieux — APPROVED** [review]

**Pull request merged**
